### ISSUE TITLE
Difficulty in adding the META-INF directory for state indexes

### ISSUE THREAD

**Issue by mbwhite** [hyperledgendary/fabric-builders#7]
If I want to have couchdb indexes for the chaincode, these need to go into the package.tgz 
This isn't really very doable with pkgcc.sh as it stands

Maybe something like `Usage: pkgcc.sh -l <label> -t <type> -m <META-INF directory> <file>` would be useful?

**Comment by jt-nti** [comment]
Fixed in #8
